use rand::distr::SampleString;
use time::PrimitiveDateTime;
use uuid::Uuid;

/// A session represents a logged-in state of a user. It is stored in Redis and used for authentication and authorization.
pub struct SessionEntity {
    /// A self-incrementing serial number as primary key.
    pub serial: i64,
    pub user_id: Uuid,
    /// An indexed string used for authentication. It is generated by [generate_session_id] function and must be unique.
    pub session_id: String,
    /// The last time expire time updates.
    pub last_refreshed: PrimitiveDateTime,
    pub expires: PrimitiveDateTime,
}

/// Generate a random session ID with length of 128 characters for [SessionEntity]. The session ID is used for authentication and must be unique.
pub fn generate_session_id() -> String {
    const LENGTH: usize = 128;
    rand::distr::Alphanumeric.sample_string(&mut rand::rng(), LENGTH)
}
